# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/gps.xdc

# XDC: imports/new/imode.xdc

# Block Designs: bd/gpsImode/gpsImode.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode || ORIG_REF_NAME==gpsImode}]

# IP: bd/gpsImode/ip/gpsImode_processing_system7_0_0/gpsImode_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_processing_system7_0_0 || ORIG_REF_NAME==gpsImode_processing_system7_0_0}]

# IP: bd/gpsImode/ip/gpsImode_newGpsIp_0_0/gpsImode_newGpsIp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_newGpsIp_0_0 || ORIG_REF_NAME==gpsImode_newGpsIp_0_0}]

# IP: bd/gpsImode/ip/gpsImode_myImode_0_0/gpsImode_myImode_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_myImode_0_0 || ORIG_REF_NAME==gpsImode_myImode_0_0}]

# IP: bd/gpsImode/ip/gpsImode_axi_uartlite_0_0/gpsImode_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_axi_uartlite_0_0 || ORIG_REF_NAME==gpsImode_axi_uartlite_0_0}]

# IP: bd/gpsImode/ip/gpsImode_processing_system7_0_axi_periph_0/gpsImode_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==gpsImode_processing_system7_0_axi_periph_0}]

# IP: bd/gpsImode/ip/gpsImode_rst_processing_system7_0_100M_0/gpsImode_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==gpsImode_rst_processing_system7_0_100M_0}]

# IP: bd/gpsImode/ip/gpsImode_xbar_0/gpsImode_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_xbar_0 || ORIG_REF_NAME==gpsImode_xbar_0}]

# IP: bd/gpsImode/ip/gpsImode_auto_pc_0/gpsImode_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_auto_pc_0 || ORIG_REF_NAME==gpsImode_auto_pc_0}]

# XDC: bd/gpsImode/ip/gpsImode_processing_system7_0_0/gpsImode_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_processing_system7_0_0 || ORIG_REF_NAME==gpsImode_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/gpsImode/ip/gpsImode_axi_uartlite_0_0/gpsImode_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_axi_uartlite_0_0 || ORIG_REF_NAME==gpsImode_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_axi_uartlite_0_0/gpsImode_axi_uartlite_0_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_axi_uartlite_0_0/gpsImode_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_axi_uartlite_0_0 || ORIG_REF_NAME==gpsImode_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_rst_processing_system7_0_100M_0/gpsImode_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==gpsImode_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_rst_processing_system7_0_100M_0/gpsImode_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==gpsImode_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_rst_processing_system7_0_100M_0/gpsImode_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_xbar_0/gpsImode_xbar_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_auto_pc_0/gpsImode_auto_pc_0_ooc.xdc

# XDC: bd/gpsImode/gpsImode_ooc.xdc
