# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/gps.xdc

# XDC: imports/new/imode.xdc

# Block Designs: bd/gpsImode/gpsImode.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode || ORIG_REF_NAME==gpsImode}]

# IP: bd/gpsImode/ip/gpsImode_processing_system7_0_0/gpsImode_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_processing_system7_0_0 || ORIG_REF_NAME==gpsImode_processing_system7_0_0}]

# IP: bd/gpsImode/ip/gpsImode_newGpsIp_0_0/gpsImode_newGpsIp_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_newGpsIp_0_0 || ORIG_REF_NAME==gpsImode_newGpsIp_0_0}]

# IP: bd/gpsImode/ip/gpsImode_axi_uartlite_0_0/gpsImode_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_axi_uartlite_0_0 || ORIG_REF_NAME==gpsImode_axi_uartlite_0_0}]

# IP: bd/gpsImode/ip/gpsImode_processing_system7_0_axi_periph_0/gpsImode_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==gpsImode_processing_system7_0_axi_periph_0}]

# IP: bd/gpsImode/ip/gpsImode_rst_processing_system7_0_100M_0/gpsImode_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==gpsImode_rst_processing_system7_0_100M_0}]

# IP: bd/gpsImode/ip/gpsImode_xbar_0/gpsImode_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_xbar_0 || ORIG_REF_NAME==gpsImode_xbar_0}]

# IP: bd/gpsImode/ip/gpsImode_myImode_0_1/gpsImode_myImode_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_myImode_0_1 || ORIG_REF_NAME==gpsImode_myImode_0_1}]

# IP: bd/gpsImode/ip/gpsImode_myip_fifo_ctrl_0_0/gpsImode_myip_fifo_ctrl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_myip_fifo_ctrl_0_0 || ORIG_REF_NAME==gpsImode_myip_fifo_ctrl_0_0}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_0_4/gpsImode_fifo_generator_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_0_4 || ORIG_REF_NAME==gpsImode_fifo_generator_0_4}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_0_5/gpsImode_fifo_generator_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_0_5 || ORIG_REF_NAME==gpsImode_fifo_generator_0_5}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_1_1/gpsImode_fifo_generator_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_1_1 || ORIG_REF_NAME==gpsImode_fifo_generator_1_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_1_2/gpsImode_fifo_generator_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_1_2 || ORIG_REF_NAME==gpsImode_fifo_generator_1_2}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_2_2/gpsImode_fifo_generator_2_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_2_2 || ORIG_REF_NAME==gpsImode_fifo_generator_2_2}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_3_1/gpsImode_fifo_generator_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_3_1 || ORIG_REF_NAME==gpsImode_fifo_generator_3_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_4_1/gpsImode_fifo_generator_4_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_4_1 || ORIG_REF_NAME==gpsImode_fifo_generator_4_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_5_1/gpsImode_fifo_generator_5_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_5_1 || ORIG_REF_NAME==gpsImode_fifo_generator_5_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_6_1/gpsImode_fifo_generator_6_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_6_1 || ORIG_REF_NAME==gpsImode_fifo_generator_6_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_7_1/gpsImode_fifo_generator_7_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_7_1 || ORIG_REF_NAME==gpsImode_fifo_generator_7_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_8_2/gpsImode_fifo_generator_8_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_8_2 || ORIG_REF_NAME==gpsImode_fifo_generator_8_2}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_10_2/gpsImode_fifo_generator_10_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_10_2 || ORIG_REF_NAME==gpsImode_fifo_generator_10_2}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_10_3/gpsImode_fifo_generator_10_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_10_3 || ORIG_REF_NAME==gpsImode_fifo_generator_10_3}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_12_0/gpsImode_fifo_generator_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_12_0 || ORIG_REF_NAME==gpsImode_fifo_generator_12_0}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_12_1/gpsImode_fifo_generator_12_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_12_1 || ORIG_REF_NAME==gpsImode_fifo_generator_12_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_14_1/gpsImode_fifo_generator_14_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_14_1 || ORIG_REF_NAME==gpsImode_fifo_generator_14_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_14_2/gpsImode_fifo_generator_14_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_14_2 || ORIG_REF_NAME==gpsImode_fifo_generator_14_2}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_16_0/gpsImode_fifo_generator_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_16_0 || ORIG_REF_NAME==gpsImode_fifo_generator_16_0}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_16_1/gpsImode_fifo_generator_16_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_16_1 || ORIG_REF_NAME==gpsImode_fifo_generator_16_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_18_0/gpsImode_fifo_generator_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_18_0 || ORIG_REF_NAME==gpsImode_fifo_generator_18_0}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_18_1/gpsImode_fifo_generator_18_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_18_1 || ORIG_REF_NAME==gpsImode_fifo_generator_18_1}]

# IP: bd/gpsImode/ip/gpsImode_fifo_generator_19_0/gpsImode_fifo_generator_19_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_19_0 || ORIG_REF_NAME==gpsImode_fifo_generator_19_0}]

# IP: bd/gpsImode/ip/gpsImode_auto_pc_0/gpsImode_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==gpsImode_auto_pc_0 || ORIG_REF_NAME==gpsImode_auto_pc_0}]

# XDC: bd/gpsImode/ip/gpsImode_processing_system7_0_0/gpsImode_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_processing_system7_0_0 || ORIG_REF_NAME==gpsImode_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/gpsImode/ip/gpsImode_axi_uartlite_0_0/gpsImode_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_axi_uartlite_0_0 || ORIG_REF_NAME==gpsImode_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_axi_uartlite_0_0/gpsImode_axi_uartlite_0_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_axi_uartlite_0_0/gpsImode_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_axi_uartlite_0_0 || ORIG_REF_NAME==gpsImode_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_rst_processing_system7_0_100M_0/gpsImode_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==gpsImode_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_rst_processing_system7_0_100M_0/gpsImode_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==gpsImode_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_rst_processing_system7_0_100M_0/gpsImode_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_xbar_0/gpsImode_xbar_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_0_4/gpsImode_fifo_generator_0_4/gpsImode_fifo_generator_0_4.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_0_4 || ORIG_REF_NAME==gpsImode_fifo_generator_0_4}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_0_4/gpsImode_fifo_generator_0_4_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_0_5/gpsImode_fifo_generator_0_5/gpsImode_fifo_generator_0_5.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_0_5 || ORIG_REF_NAME==gpsImode_fifo_generator_0_5}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_0_5/gpsImode_fifo_generator_0_5_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_1_1/gpsImode_fifo_generator_1_1/gpsImode_fifo_generator_1_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_1_1 || ORIG_REF_NAME==gpsImode_fifo_generator_1_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_1_1/gpsImode_fifo_generator_1_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_1_2/gpsImode_fifo_generator_1_2/gpsImode_fifo_generator_1_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_1_2 || ORIG_REF_NAME==gpsImode_fifo_generator_1_2}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_1_2/gpsImode_fifo_generator_1_2_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_2_2/gpsImode_fifo_generator_2_2/gpsImode_fifo_generator_2_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_2_2 || ORIG_REF_NAME==gpsImode_fifo_generator_2_2}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_2_2/gpsImode_fifo_generator_2_2_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_3_1/gpsImode_fifo_generator_3_1/gpsImode_fifo_generator_3_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_3_1 || ORIG_REF_NAME==gpsImode_fifo_generator_3_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_3_1/gpsImode_fifo_generator_3_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_4_1/gpsImode_fifo_generator_4_1/gpsImode_fifo_generator_4_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_4_1 || ORIG_REF_NAME==gpsImode_fifo_generator_4_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_4_1/gpsImode_fifo_generator_4_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_5_1/gpsImode_fifo_generator_5_1/gpsImode_fifo_generator_5_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_5_1 || ORIG_REF_NAME==gpsImode_fifo_generator_5_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_5_1/gpsImode_fifo_generator_5_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_6_1/gpsImode_fifo_generator_6_1/gpsImode_fifo_generator_6_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_6_1 || ORIG_REF_NAME==gpsImode_fifo_generator_6_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_6_1/gpsImode_fifo_generator_6_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_7_1/gpsImode_fifo_generator_7_1/gpsImode_fifo_generator_7_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_7_1 || ORIG_REF_NAME==gpsImode_fifo_generator_7_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_7_1/gpsImode_fifo_generator_7_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_8_2/gpsImode_fifo_generator_8_2/gpsImode_fifo_generator_8_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_8_2 || ORIG_REF_NAME==gpsImode_fifo_generator_8_2}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_8_2/gpsImode_fifo_generator_8_2_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_10_2/gpsImode_fifo_generator_10_2/gpsImode_fifo_generator_10_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_10_2 || ORIG_REF_NAME==gpsImode_fifo_generator_10_2}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_10_2/gpsImode_fifo_generator_10_2_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_10_3/gpsImode_fifo_generator_10_3/gpsImode_fifo_generator_10_3.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_10_3 || ORIG_REF_NAME==gpsImode_fifo_generator_10_3}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_10_3/gpsImode_fifo_generator_10_3_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_12_0/gpsImode_fifo_generator_12_0/gpsImode_fifo_generator_12_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_12_0 || ORIG_REF_NAME==gpsImode_fifo_generator_12_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_12_0/gpsImode_fifo_generator_12_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_12_1/gpsImode_fifo_generator_12_1/gpsImode_fifo_generator_12_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_12_1 || ORIG_REF_NAME==gpsImode_fifo_generator_12_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_12_1/gpsImode_fifo_generator_12_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_14_1/gpsImode_fifo_generator_14_1/gpsImode_fifo_generator_14_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_14_1 || ORIG_REF_NAME==gpsImode_fifo_generator_14_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_14_1/gpsImode_fifo_generator_14_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_14_2/gpsImode_fifo_generator_14_2/gpsImode_fifo_generator_14_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_14_2 || ORIG_REF_NAME==gpsImode_fifo_generator_14_2}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_14_2/gpsImode_fifo_generator_14_2_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_16_0/gpsImode_fifo_generator_16_0/gpsImode_fifo_generator_16_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_16_0 || ORIG_REF_NAME==gpsImode_fifo_generator_16_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_16_0/gpsImode_fifo_generator_16_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_16_1/gpsImode_fifo_generator_16_1/gpsImode_fifo_generator_16_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_16_1 || ORIG_REF_NAME==gpsImode_fifo_generator_16_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_16_1/gpsImode_fifo_generator_16_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_18_0/gpsImode_fifo_generator_18_0/gpsImode_fifo_generator_18_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_18_0 || ORIG_REF_NAME==gpsImode_fifo_generator_18_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_18_0/gpsImode_fifo_generator_18_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_18_1/gpsImode_fifo_generator_18_1/gpsImode_fifo_generator_18_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_18_1 || ORIG_REF_NAME==gpsImode_fifo_generator_18_1}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_18_1/gpsImode_fifo_generator_18_1_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_19_0/gpsImode_fifo_generator_19_0/gpsImode_fifo_generator_19_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==gpsImode_fifo_generator_19_0 || ORIG_REF_NAME==gpsImode_fifo_generator_19_0}] {/U0 }]/U0 ]]

# XDC: bd/gpsImode/ip/gpsImode_fifo_generator_19_0/gpsImode_fifo_generator_19_0_ooc.xdc

# XDC: bd/gpsImode/ip/gpsImode_auto_pc_0/gpsImode_auto_pc_0_ooc.xdc

# XDC: bd/gpsImode/gpsImode_ooc.xdc
